# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"!\n\x10InferenceRequest\x12\r\n\x05image\x18\x01 \x03(\x0c\"\'\n\x11InferenceResponse\x12\x12\n\nprediction\x18\x01 \x03(\r2G\n\x0fInferenceServer\x12\x34\n\tinference\x12\x11.InferenceRequest\x1a\x12.InferenceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=19
  _globals['_INFERENCEREQUEST']._serialized_end=52
  _globals['_INFERENCERESPONSE']._serialized_start=54
  _globals['_INFERENCERESPONSE']._serialized_end=93
  _globals['_INFERENCESERVER']._serialized_start=95
  _globals['_INFERENCESERVER']._serialized_end=166
# @@protoc_insertion_point(module_scope)
